JDP190304-28 /solve "2 klasy Order w masterze"
pplutap/JDP-1903-04 pull request #11
Opened 2019-04-02 12:10 UTC by SlawomirJablonski

propozycja nowej klasy Order, zaproponowałem tez w związku z tym zmianę w CartController tzn dodatkowy parametr userId w metodzie createOrder cartcontrolerar:
@PostMapping(value = "createOrder", consumes = APPLICATION_JSON_VALUE)
    public void createOrder(@RequestBody CartDto cartDto, @RequestParam Long userId) {
        Order newOrder = new Order(userId, cartMapper.mapToCart(cartDto));
    }

2019-04-02 21:09 UTC, maciek-prokopiuk commented
W komentarzach na Github można używać składni `Markdown`. Warto się zapoznać z podstawami by ładnie formatować kod.

2019-04-02 21:19 UTC, maciek-prokopiuk requested changes

2019-04-02 21:19 UTC, maciek-prokopiuk commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void createOrder(@RequestBody CartDto cartDto, @RequestParam Long userId) {
przekazywanie userId jako `RequestParam` jest dość słabym rozwiązaniem. Używasz tu POSTa, więc wszystkie Twoje dane potrzebne do requestu powinny pójść w RequestBody.

2019-04-02 21:19 UTC, maciek-prokopiuk commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void createOrder(@RequestBody CartDto cartDto, @RequestParam Long userId) {
Poza tym ze schematu bazy danych, który widziałem wynika, że encja `Cart powinna już zawierać `userId`, więc `CartDto` również może je posiadać.

2019-04-03 06:37 UTC, SlawomirJablonski commented
proszę poprawki

2019-04-03 20:05 UTC, maciek-prokopiuk approved these changes

2019-04-03 22:08 UTC, merged