Cart Entity + entity sąsiednie do żaleźnosci ManyToMany i OneToOne
pplutap/JDP-1903-04 pull request #13
Opened 2019-04-04 13:59 UTC by DonnieDarko8881

dodałem też Entity Product i User, ale tylko w stopniu pozwalającej zrobić mi zaleznosci ManytoMany i OneToOne

2019-04-05 07:44 UTC, erwinMuz commented
Masz konflikty + testy nie dzialaja

2019-04-05 07:45 UTC, erwinMuz requested changes

2019-04-05 07:45 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/domain/users/User.java
> +    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
fetch = FetchType.EAGER - niepotrzebne
Dla  @OneToOne to doyslna wartosc

2019-04-05 08:53 UTC, maciek-prokopiuk commented on src/main/java/com/kodilla/ecommercee/service/DbCartService.java
> +public class DbCartService {
Może po prostu `CartService`?

2019-04-06 08:20 UTC, maciek-prokopiuk approved these changes

2019-04-06 22:53 UTC, closed without merging