Jdp190304 12 encja product implementacja
pplutap/JDP-1903-04 pull request #16
Opened 2019-04-05 17:37 UTC by bcaban

Implementacja Encji Product + sąsiednie Encje z zależnościami + ProductRepository + ProductService

2019-04-05 22:33 UTC, DonnieDarko8881 commented on src/main/java/com/kodilla/ecommercee/domain/carts/Cart.java
> +
Hej,
Myślę że można: 
@Column
    private String name usunąć. Name jest niepotrzebne w cart plus ja też tego nie mam :)

2019-04-05 22:35 UTC, DonnieDarko8881 commented on src/main/java/com/kodilla/ecommercee/domain/products/Product.java
> +
lepiej nazwać pole "deleted" z tego względu ze getter będzie się nazywał isDeleted.  @maciek-prokopiuk  wspominał o nazewnictwie pól dotyczących boolean

2019-04-05 22:35 UTC, DonnieDarko8881 commented on src/main/java/com/kodilla/ecommercee/domain/products/Product.java
> +    }
i tu też  konsekwetnie powinno być "deleted"

2019-04-05 23:38 UTC, dkoplenski commented on src/main/java/com/kodilla/ecommercee/domain/products/Product.java
> +    }
relacja @manyToOne prosze zamień nazwę pola(NIE KOLUMNY!) z groupId na group :)

2019-04-06 07:51 UTC, maciek-prokopiuk commented on src/main/java/com/kodilla/ecommercee/domain/products/Product.java
> +
👍

2019-04-06 08:08 UTC, maciek-prokopiuk requested changes

2019-04-06 08:08 UTC, maciek-prokopiuk commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
>      @Autowired
zamień wstrzykiwanie przez pola na wstrzykiwanie przez konstruktor

2019-04-06 09:40 UTC, bcaban commented
Dzięki chłopaki za wskazówki, zastosowałem zmiany w oparciu o nie :)

2019-04-06 16:50 UTC, maciek-prokopiuk approved these changes

2019-04-06 22:46 UTC, dblooper approved these changes

2019-04-06 22:47 UTC, DonnieDarko8881 approved these changes
Teraz cały jest konsekwentny i wszystko działa :)

2019-04-06 22:52 UTC, merged