JDP190304-18_group_encja_testy
pplutap/JDP-1903-04 pull request #19
Opened 2019-04-07 17:56 UTC by DonnieDarko8881

Testy przeszły pozytwynie :) 
Tworzą się Id zarówno groupy jak i produktów.

2019-04-08 12:57 UTC, maciek-prokopiuk requested changes

2019-04-08 12:57 UTC, maciek-prokopiuk commented on src/test/java/com/kodilla/ecommercee/domain/orders/OrderEntityTestSuite.java
> +    public void shouldReturnNotNullGroupIdAndProductsId(){
`shouldReturnNotNullGroupIdAndProductIds` raczej spotyka się nazwy w stylu ProductIds, a nie ProductsId. Ta druga sugeruje, że jakiś zbiór produktów ma jedno id

2019-04-08 12:57 UTC, maciek-prokopiuk commented on src/test/java/com/kodilla/ecommercee/domain/orders/OrderEntityTestSuite.java
> +        List<Product> smartphonesList = new ArrayList<>();
to bym nazwał smartphones

2019-04-08 12:57 UTC, maciek-prokopiuk commented on src/test/java/com/kodilla/ecommercee/domain/orders/OrderEntityTestSuite.java
> +        Group smartphones = new Group("smartphones",smartphonesList);
a to, smartphonesGroup

2019-04-08 12:57 UTC, maciek-prokopiuk commented on src/test/java/com/kodilla/ecommercee/domain/orders/OrderEntityTestSuite.java
> +        Group smartphones = new Group("smartphones",smartphonesList);
dla mnie byłoby czytelniejsze nieco. ale to jest pierdoła ;)

2019-04-08 12:57 UTC, maciek-prokopiuk commented on src/test/java/com/kodilla/ecommercee/domain/orders/OrderEntityTestSuite.java
> +    public void shouldReturnNotNullGroupIdAndProductsId(){
przydałyby się jakieś testy error handlingu oraz z różnymi danymi. przekazanie którychś produktów jako nullowe itd. ogólnie masz jeden przypadek testowy - małoo

2019-04-08 23:50 UTC, DonnieDarko8881 commented on src/main/java/com/kodilla/ecommercee/domain/groups/Group.java
>  public class Group {
Dodałem @Table ze względu z nazwą ze wzgledu na to, ze nie chciały wykonwyać się servicy takie jak count , czy findAll, wpisałem błąd w google i wyszło na to że musze dodać @Table i rzeczywiscie teraz działają nie tylko save i dalete ale reszta rzeczy takie jak count() i findAll() też

2019-04-08 23:50 UTC, DonnieDarko8881 commented on src/main/java/com/kodilla/ecommercee/domain/groups/Group.java
>  }
To nie powinno się dodać. To jest w masterze.

2019-04-08 23:51 UTC, DonnieDarko8881 commented on src/main/java/com/kodilla/ecommercee/domain/orders/Item.java
>      @JoinColumn(name = "order_id")
i to tez nie powinno byc w tym commicie, tez jest ta zmaina w masterze naniesiona

2019-04-08 23:51 UTC, DonnieDarko8881 commented on src/main/java/com/kodilla/ecommercee/domain/orders/Order.java
>  }
tak samo to

2019-04-10 06:23 UTC, maciek-prokopiuk approved these changes

2019-04-10 17:30 UTC, merged