Jdp190304-1 productController
pplutap/JDP-1903-04 pull request #2
Opened 2019-03-27 21:20 UTC by DonnieDarko8881

2019-03-28 15:54 UTC, erwinMuz requested changes

2019-03-28 15:54 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +    public void setName(String name) {
Usuń gettery i settery - używasz lomboka

2019-03-28 15:54 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    List<ProductDto> products = new ArrayList<>();
private

2019-03-28 15:54 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +        if (products.isEmpty()) {
Przenieś  tworzenie computer i laptop tutaj.  Metody prywatne powinny być na końcu klasy.

2019-03-28 15:54 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/ProductController.java
>  public class ProductController {
Przenieś  kontroler do pakietu controller

2019-03-28 15:59 UTC, erwinMuz requested changes

2019-03-28 15:59 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public ProductDto createProduct(@RequestBody ProductDto productDto) {
Void

2019-03-28 17:53 UTC, DonnieDarko8881 commented
@erwinMuz 
Naniosłem poprawki
zmieniłem w createProduct na void
przeniosełem metodę prywatną na dół klasy,
tworzenie computer i laptor umiesciłem w klasie prywatnej
i usunąłem settery i gettery z klasy ProductDto  dodając adnotację @Setter

2019-03-28 20:01 UTC, erwinMuz requested changes

2019-03-28 20:01 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        computer = new ProductDto(1L, "computer", "test");
wystarczy jak tutaj zdeniujesz coputer i laptop - linie 14-15 sa niepotrzebne

2019-03-29 16:35 UTC, DonnieDarko8881 commented
@erwinMuz 
przeniosłem computer i laptop całkowicie do prywatnej metody 
mam nadzieje że o to chodziło :) 
Dzięki za poprawki :)

2019-03-29 20:49 UTC, erwinMuz commented
czy ten PR jest potrzbny? Wszystkie zmiany dodales do pierwszego na branchu "build_gradlew_lambook_msql"

2019-03-29 21:38 UTC, merged