JDP-1903-04_JDP190304-3_cartController
pplutap/JDP-1903-04 pull request #3
Opened 2019-03-28 18:51 UTC by dkoplenski

Wstęna implementacja CartControllera, powinien zwracać sztucznie zaimplementowane dane.

2019-03-28 20:56 UTC, erwinMuz requested changes
Brakuje : 
- utworzenie zamówienia na podstawie koszyka

Zamiast przechowywac Cart jako atrybut CartController  dodaj parametr np cardId do odpowiednich metod

2019-03-28 20:56 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getProductFromCart")
ta metoda jest chyba niepotrzebna?

2019-03-29 16:47 UTC, DonnieDarko8881 commented
@dkoplenski 
hej u mnie Klasa ProductDto 
wygląda tak

"@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class ProductDto {
    private  Long productId;
    private  String name;
    private  String description;
}"

warto by było ją zrobić tak samo bo będziemy mieli konflikt, a w sesnie ja robiłem ProductController dlato uważam że ProductDto nalezy do mnie heheh :)

2019-03-29 21:04 UTC, dkoplenski commented
Poprawione, proszę o weryfikację. Dzięki chłopaki za uwagi

2019-03-29 21:11 UTC, dkoplenski commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getProductFromCart")
tak jasne, zagalopowalem sie :)

2019-03-30 17:03 UTC, erwinMuz commented
sa konflikty + nie przechodza testy,

2019-03-31 20:01 UTC, erwinMuz requested changes
Zamiast RequestMapping uzyj @PostMapping, @GetMapping, @PutMapping ... - bedzie spojnie z reszta endpointow

2019-03-31 20:01 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public List<ProductDto> getProductsFromCart() {
brakuje parametru z jakiego koszyka maja byc pobrane produkty

2019-03-31 20:01 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void addItemToCart(@RequestBody ProductDto productDto) {
brakuje parametru do jakiego koszyka ma byc dodany pordukt

2019-03-31 20:01 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void deleteItemFromCart(@RequestParam Long itemId) {
tutaj tz brak parametru koszyka

2019-04-01 14:53 UTC, erwinMuz requested changes

2019-04-01 14:53 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private List<Product> products = new ArrayList<>();
wykorzystaj ProductDto i mozna mergowac :)

2019-04-01 15:19 UTC, dkoplenski commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private List<Product> products = new ArrayList<>();
Dzięki nie zwrocilem uwagi :)

2019-04-01 18:29 UTC, erwinMuz approved these changes

2019-04-01 18:37 UTC, merged