JDP190304-22 GroupController - rzeczywista implementacja metod
pplutap/JDP-1903-04 pull request #31
Opened 2019-04-10 16:23 UTC by bcaban

2019-04-10 18:32 UTC, DonnieDarko8881 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +
serwisy chyba nalezy wstrzyknąc najlepiej przez konstruktor

2019-04-10 20:50 UTC, maciek-prokopiuk commented on src/main/java/com/kodilla/ecommercee/controller/exceptions/GroupNotFoundException.java
> +public class GroupNotFoundException extends Exception {
RuntimeException

2019-04-10 20:51 UTC, maciek-prokopiuk commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +    private GroupRepository groupRepository;
private final

2019-04-10 20:52 UTC, maciek-prokopiuk commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    private GroupService groupService;
private final

2019-04-10 20:52 UTC, maciek-prokopiuk requested changes
Drobne poprawki

2019-04-13 06:55 UTC, maciek-prokopiuk commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      private GroupMapper groupMapper;
a group mapper nie powinien być final?

2019-04-13 06:55 UTC, maciek-prokopiuk approved these changes

2019-04-13 08:32 UTC, bcaban commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      private GroupMapper groupMapper;
Faktycznie, przeoczyłem, już poprawiam

2019-04-13 08:38 UTC, merged