Wstępna implemętacja encji
pplutap/JDP-1903-04 pull request #8
Opened 2019-04-01 12:26 UTC by DMizyn

pplication.properties nie powinno zostać wysłane, ale jakoś się wysłało.
Proszę o sugestę czy zostawiamy:
    @ManyToMany(cascade = CascadeType.ALL)
    @Column(name = "user")
    List<User> users = new ArrayList<>();

Czy raczej coś w stylu:
String userId;

2019-04-01 15:12 UTC, erwinMuz requested changes
usun niepotrzene pliki + napraw testy

2019-04-01 15:12 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    @ManyToMany(cascade = CascadeType.ALL)
czy napewno @ManyToMany?

2019-04-02 21:54 UTC, DMizyn commented
Testy wywala przez CartController oraz OrderController.

2019-04-03 20:07 UTC, maciek-prokopiuk commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @Autowired
wszystkie pola wstrzyknij przez konstruktor

2019-04-03 20:09 UTC, maciek-prokopiuk commented
Pierwsze pytanie. Czemu w jednym PR jest tak dużo zmian? Większość rzeczy, które tu masz są już w masterze. Np CartController w tym PR ma złe pathy, a w masterze już poprawne. Według mnie ten PR jest do zamknięcia. Same zmiany, które miały być w nim zrobione powinny zostać naniesione na najnowszego mastera.

2019-04-06 08:21 UTC, closed without merging